version: "3.9"
services:
  web:
    build: .  
    ports:
      - "${PORT}:${PORT}"  
    environment:
      - DB_HOST=db  
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER} 
      - DB_PASSWORD=${DB_PASSWORD}  
      - DB_DATABASE=${DB_DATABASE}  
    depends_on:
      - db  
  db:
    image: postgres:14  
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}   
      - POSTGRES_DB=${DB_DATABASE}  
    ports:
      - "${DB_PORT}:${DB_PORT}"       
    volumes:
      - postgres_data:/var/lib/postgresql/data  

volumes:
  postgres_data:
